modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="fractured_reality"
version="1.2.03"
displayName="Fractured Reality"
displayURL="https://modrinth.com/project/vZ2PEXzS"
logoFile="logo.png"
credits="Presenter, Moonbreaker & Faceless voicelines by https://www.youtube.com/@MIAparadisetv"
authors="Jorge M."
description="As reality breaks and the sky cracks apart, mysterious beings are unleashed upon the world. The cycle of day and night breaks, the rain disappears, and the mobs spawn less and less. The players have to shelter from the gravity fluctuations pulling them up into the sky. It is up to the players to solve what happened and fix their world. The players will have to solve puzzles and find a way to go above and beyond. Once the world is repaired, everything will go back to normal, but not for long. "

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.fractured_reality]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.fractured_reality]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.fractured_reality]]
    modId="jei"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration